CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER

  BEGIN;
  CREATE TABLE IF NOT EXISTS DOC_SIMILARITY(
		ALGO_TYPE varchar,
		DOC_ID_1 varchar,
		DOC_ID_2 varchar,
		SIMILARITY float
  );

  COMMIT;

    BEGIN;
	CREATE TABLE IF NOT EXISTS DOCUMENT(
		DOC_SRC varchar NOT NULL,
		DOC_ID  varchar NOT NULL PRIMARY KEY,
		TIMESTAMP timestamp NOT NULL
  );

  COMMIT;

      BEGIN;
	CREATE TABLE IF NOT EXISTS DOC_PROCESSING(
		PROCESS_ID varchar,
		DOC_ID varchar,
		STATUS varchar
  );

  COMMIT;


	BEGIN;
	CREATE TABLE IF NOT EXISTS RUN_LOGS(
		PROCESS_TYPE varchar,
		TIMESTAMP timestamp
  );

  COMMIT;


EOSQL